server:
  port: 8080
  servlet:
    context-path: /axisbank/v1
spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    active: dev
  application:
    name=Axis-Bank-Backend
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/axisbank_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      connection-timeout: 30000
      idle-timeout: 36000000       # 10 hours (or set to 0 to disable)
      max-lifetime: 36000000       # 10 hours
      pool-name: axis-bank
  mail:
    host: smtp.gmail.com
    port: 587
    username: wadnereomkar@gmail.com
    password: neyk hlvs dedw aqkq
    properties:
      mail:
        transport:
          protocol: smtp                 # Protocol to use
        smtp:
          auth: true                     # Enable authentication
          starttls:
            enable: true                 # Enable STARTTLS for secure connection
          connectiontimeout: 5000        # Connection timeout in milliseconds
          timeout: 5000                  # Socket timeout in milliseconds
          writetimeout: 5000             # Write timeout in milliseconds
          pool: true                     # Enable connection pooling
          poolsize: 5                    # Optional: Maximum connections in the pool (custom property)
management:
  endpoints:
    web:
      exposure:
        include: "*"   # Enable all actuator endpoints
      base-path: /actuator   # Change base path (default: /actuator)
  endpoint:
    health:
      show-details: always   # Always show full health details
  info:
    env:
      enabled: true          # Allow app info from properties

info:
  app:
    name: Axis Bank Backend
    version: 1.0.0
    description: Spring Boot Banking Application

app:
  jwt:
    private-key-path: classpath:keys/jwt_private_pkcs8.pem
    public-key-path: classpath:keys/jwt_public.pem
    access-token-validity-seconds: 900    #15 minutes
    refresh-token-validity-seconds: 1209600  #14 days

logging:
  level:
    root: INFO

otp:
  ttlSeconds: 300
  cooldownSeconds: 60
  maxVerifyAttempts: 5
  maxRequestPerHour: 10
  maxRequestReachedTime: 3600
  hmacSecret: VshI/FeERC5ng21fwq0MhNLXbOpP5qe7uJQaN20FXHA=

user:
  signupTime: 900